version: '3.8'

services:
  frontend:
    build: ./web-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
    environment:
      BACKEND_URL: http://backend:3001

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    environment:
      DATABASE_URL: ${DATABASE_URL}

networks:
  mynetwork:
    driver: bridge
